name: ohe_atd_app
description: OHE ATD Smart Tool
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  image: ^4.0.17
  path_provider: ^2.1.2
  permission_handler: ^11.0.1

flutter:
  uses-material-design: true
